DROP TABLE IF EXISTS event_similarities;
DROP TABLE IF EXISTS user_actions;

-- =====================================================================================================================

CREATE TABLE IF NOT EXISTS event_similarities (
 event_a BIGINT NOT NULL,
 event_b BIGINT NOT NULL,
 score REAL NOT NULL,
 timestamp TIMESTAMP NOT NULL,
 PRIMARY KEY (event_a, event_b)
);

COMMENT ON TABLE event_similarities IS 'Содержит информацию о сходствах мероприятий';
COMMENT ON COLUMN event_similarities.event_a IS 'Идентификатор первого мероприятия';
COMMENT ON COLUMN event_similarities.event_b IS 'Идентификатор второго мероприятия';
COMMENT ON COLUMN event_similarities.score IS 'Значение рассчитанного сходства мероприятий';
COMMENT ON COLUMN event_similarities.timestamp IS 'Метка времени, когда было совершено действие, инициирующее расчет';

-- =====================================================================================================================

CREATE TABLE IF NOT EXISTS user_actions (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 user_id BIGINT NOT NULL,
 event_id BIGINT NOT NULL,
 action_type VARCHAR(10) NOT NULL,
 timestamp TIMESTAMP NOT NULL
);

ALTER TABLE user_actions DROP CONSTRAINT IF EXISTS user_action_type_check;
ALTER TABLE user_actions ADD CONSTRAINT user_action_type_check CHECK (action_type IN ('VIEW', 'REGISTER', 'LIKE'));

COMMENT ON TABLE user_actions IS 'Действие пользователя';
COMMENT ON COLUMN user_actions.id IS 'Уникальный идентификатор действия пользователя';
COMMENT ON COLUMN user_actions.user_id IS 'Идентификатор пользователя';
COMMENT ON COLUMN user_actions.event_id IS 'Идентификатор события';
COMMENT ON COLUMN user_actions.action_type IS 'Тип действия пользователя';
COMMENT ON COLUMN user_actions.timestamp IS 'Время совершения действия';

-- =====================================================================================================================