DROP TABLE IF EXISTS categories;

CREATE TABLE IF NOT EXISTS categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(50) NOT NULL UNIQUE
);

ALTER TABLE categories DROP CONSTRAINT IF EXISTS categories_name_check;
ALTER TABLE categories ADD CONSTRAINT categories_name_check CHECK (TRIM(name) <> '' AND LENGTH(TRIM(name)) >= 2);

COMMENT ON TABLE categories IS 'Содержит информацию о категориях';
COMMENT ON COLUMN categories.id IS 'Уникальный идентификатор категории';
COMMENT ON COLUMN categories.name IS 'Название категории';