services:
  category-service:
    build: core/category-service
    image: category-service
    container_name: category-service
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:postgresql://category-service-db:5432/category-service
    depends_on:
      category-service-db:
        condition: service_healthy
      config-server:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "--fail", "--silent", "http://discovery-server:8761/eureka/v2/apps/category-service" ]
      interval: 15s
      timeout: 3s
      retries: 10
      start_period: 15s
    restart: on-failure

  category-service-db:
    image: postgres:16.1
    container_name: category-service-db
    ports:
      - "6554:5432"
    environment:
      - POSTGRES_DB=category-service
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=1qaz!QAZ
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10

  config-server:
    build: infra/config-server
    image: config-server
    container_name: config-server
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
    depends_on:
      discovery-server:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "--fail", "--silent", "http://discovery-server:8761/eureka/v2/apps/config-server" ]
      interval: 15s
      timeout: 3s
      retries: 10
      start_period: 5s
    restart: on-failure

  discovery-server:
    build: infra/discovery-server
    image: discovery-server
    container_name: discovery-server
    ports:
      - "8761:8761"
    healthcheck:
      test: [ "CMD", "curl", "--fail", "--silent", "http://localhost:8761/actuator/health" ]
      interval: 15s
      timeout: 3s
      retries: 10
      start_period: 5s

  gateway-server:
    build: infra/gateway-server
    image: gateway-server
    container_name: gateway-server
    ports:
      - "8080:8080"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
    depends_on:
      category-service:
        condition: service_healthy
      config-server:
        condition: service_healthy
      main-service:
        condition: service_healthy
      user-service:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "--fail", "--silent", "http://discovery-server:8761/eureka/v2/apps/gateway-server" ]
      interval: 15s
      timeout: 3s
      retries: 10
      start_period: 5s
    restart: on-failure

  main-service:
    build: core/main-service
    image: main-service
    container_name: main-service
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:postgresql://main-service-db:5432/main-service
    depends_on:
      category-service:
        condition: service_healthy
      config-server:
        condition: service_healthy
      main-service-db:
        condition: service_healthy
      stats-server:
        condition: service_healthy
      user-service:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "--fail", "--silent", "http://discovery-server:8761/eureka/v2/apps/main-service" ]
      interval: 15s
      timeout: 3s
      retries: 10
      start_period: 10s
    restart: on-failure

  main-service-db:
    image: postgres:16.1
    container_name: main-service-db
    ports:
      - "6555:5432"
    environment:
      - POSTGRES_DB=main-service
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=1qaz!QAZ
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10

  stats-server:
    build: stats/stats-server
    image: stats-server
    container_name: stats-server
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-server-db:5432/stats-server
    depends_on:
      discovery-server:
        condition: service_healthy
      stats-server-db:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "--fail", "--silent", "http://discovery-server:8761/eureka/v2/apps/stats-server" ]
      interval: 15s
      timeout: 3s
      retries: 10
      start_period: 15s
    restart: on-failure

  stats-server-db:
    image: postgres:16.1
    container_name: stats-server-db
    ports:
      - "6556:5432"
    environment:
      - POSTGRES_DB=stats-server
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=1qaz!QAZ
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10

  user-service:
    build: core/user-service
    image: user-service
    container_name: user-service
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:postgresql://user-service-db:5432/user-service
    depends_on:
      config-server:
        condition: service_healthy
      user-service-db:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "--fail", "--silent", "http://discovery-server:8761/eureka/v2/apps/user-service" ]
      interval: 15s
      timeout: 3s
      retries: 10
      start_period: 15s
    restart: on-failure

  user-service-db:
    image: postgres:16.1
    container_name: user-service-db
    ports:
      - "6557:5432"
    environment:
      - POSTGRES_DB=user-service
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=1qaz!QAZ
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10