services:
  category-service-db:
    image: postgres:16.1
    container_name: category-service-db
    ports:
      - "6554:5432"
    environment:
      - POSTGRES_DB=category-service
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=1qaz!QAZ
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10

  main-service-db:
    image: postgres:16.1
    container_name: main-service-db
    ports:
      - "6555:5432"
    environment:
      - POSTGRES_DB=main-service
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=1qaz!QAZ
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10

  stats-server-db:
    image: postgres:16.1
    container_name: stats-server-db
    ports:
      - "6556:5432"
    environment:
      - POSTGRES_DB=stats-server
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=1qaz!QAZ
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10

  user-service-db:
    image: postgres:16.1
    container_name: user-service-db
    ports:
      - "6557:5432"
    environment:
      - POSTGRES_DB=user-service
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=1qaz!QAZ
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10