syntax = "proto3";

package stats.service.dashboard;

import "stats/message/interactions_count_request.proto";
import "stats/message/recommended_event.proto";
import "stats/message/similar_events_request.proto";
import "stats/message/user_predictions_request.proto";

option java_multiple_files = true;
option java_package = "stats.service.dashboard";

service RecommendationsController {
  rpc GetRecommendationsForUser (stats.message.analyzer.UserPredictionsRequestProto) returns (stream stats.message.analyzer.RecommendedEventProto);
  rpc GetSimilarEvents (stats.message.analyzer.SimilarEventsRequestProto) returns (stream stats.message.analyzer.RecommendedEventProto);
  rpc GetInteractionsCount (stats.message.analyzer.InteractionsCountRequestProto) returns (stream stats.message.analyzer.RecommendedEventProto);
}