eureka:
  client:
    fetchRegistry: false
    registerWithEureka: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  instance:
    hostname: localhost
  server:
    response-cache-update-interval-ms: 5000

logging:
  level:
    com.netflix.discovery: OFF
    com.netflix.eureka: OFF

server:
  port: 8761

spring:
  application:
    name: eureka-server