DROP TABLE IF EXISTS requests;

CREATE TABLE IF NOT EXISTS requests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  event_id BIGINT NOT NULL,
  requester_id BIGINT NOT NULL,
  status VARCHAR(10) NOT NULL,
  CONSTRAINT requests_event_id_requester_id_unique_idx UNIQUE (event_id, requester_id)
);

ALTER TABLE requests DROP CONSTRAINT IF EXISTS request_status_check;
ALTER TABLE requests ADD CONSTRAINT request_status_check CHECK (status IN ('PENDING', 'CONFIRMED', 'CANCELED', 'REJECTED'));

COMMENT ON TABLE requests IS 'Содержит информацию о заявках на участие в событиях';
COMMENT ON COLUMN requests.id IS 'Уникальный идентификатор заявки на участие в событии';
COMMENT ON COLUMN requests.created IS 'Дата и время создания заявки на участие в событии';
COMMENT ON COLUMN requests.event_id IS 'Идентификатор события';
COMMENT ON COLUMN requests.requester_id IS 'Идентификатор пользователя, отправившего заявку';
COMMENT ON COLUMN requests.status IS 'Статус заявки на участие в событии';