logging:
  level:
    org.springframework.cloud.gateway: DEBUG

server:
  port: 8080

spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      httpclient:
        wiretap: true
      httpserver:
        wiretap: true
      routes:
        - id: category_service_route
          uri: lb://category-service
          predicates:
            - Path=/admin/categories/**,/categories/**
        - id: main_service_route
          uri: lb://main-service
          predicates:
            - Path=/admin/compilations/**,/admin/events/**,/comments/**,/compilations/**,/events/**,/users/**
        - id: user_service_route
          uri: lb://user-service
          predicates:
            - Path=/admin/users/**