logging:
  level:
    org.springframework.cloud.gateway: DEBUG

server:
  port: 8080

spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      httpclient:
        wiretap: true
      httpserver:
        wiretap: true
      routes:
        - id: category_service_route
          uri: lb://category-service
          predicates:
            - Path=/admin/categories, /admin/categories/{categoryId}, /categories, /categories/{categoryId}
        - id: event_service_route
          uri: lb://event-service
          predicates:
            - Path=/admin/events, /admin/events/{eventId}, /events, /events/{eventId}, /users/{userId}/events, /users/{userId}/events/{eventId}
        - id: main_service_route
          uri: lb://main-service
          predicates:
            - Path= /admin/compilations, /admin/compilations/{compilationId}, /comments, /compilations, /compilations/{compilationId}, /users/{userId}/comments, /users/{userId}/comments/{commentId}
        - id: request_service_route
          uri: lb://request-service
          predicates:
            - Path= /users/{userId}/events/{eventId}/requests, /users/{userId}/requests, /users/{userId}/requests/{requestId}/cancel
        - id: user_service_route
          uri: lb://user-service
          predicates:
            - Path=/admin/users, /admin/users/{userId}