DROP TABLE IF EXISTS events;

CREATE TABLE IF NOT EXISTS events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_on TIMESTAMP NOT NULL,
  initiator_id BIGINT NOT NULL,
  title VARCHAR(120) NOT NULL,
  annotation VARCHAR(2000) NOT NULL,
  description VARCHAR(7000) NOT NULL,
  event_date TIMESTAMP NOT NULL,
  category_id BIGINT NOT NULL,
  location VARCHAR(50) NOT NULL,
  published_on TIMESTAMP,
  paid BOOLEAN NOT NULL DEFAULT FALSE,
  participant_limit INTEGER NOT NULL DEFAULT 0,
  request_moderation BOOLEAN NOT NULL DEFAULT TRUE,
  confirmed_requests INTEGER NOT NULL DEFAULT 0,
  state VARCHAR(10) NOT NULL
);

ALTER TABLE events DROP CONSTRAINT IF EXISTS events_title_check;
ALTER TABLE events DROP CONSTRAINT IF EXISTS events_annotation_check;
ALTER TABLE events DROP CONSTRAINT IF EXISTS events_description_check;
ALTER TABLE events DROP CONSTRAINT IF EXISTS events_state_check;

ALTER TABLE events ADD CONSTRAINT events_title_check CHECK (TRIM(title) <> '' AND LENGTH(TRIM(title)) >= 3);
ALTER TABLE events ADD CONSTRAINT events_annotation_check CHECK (TRIM(annotation) <> '' AND LENGTH(TRIM(annotation)) >= 20);
ALTER TABLE events ADD CONSTRAINT events_description_check CHECK (TRIM(description) <> '' AND LENGTH(TRIM(description)) >= 20);
ALTER TABLE events ADD CONSTRAINT events_state_check CHECK (state IN ('PENDING', 'PUBLISHED', 'REJECTED', 'CANCELED'));

COMMENT ON TABLE events IS 'Содержит информацию о событиях';
COMMENT ON COLUMN events.id IS 'Уникальный идентификатор события';
COMMENT ON COLUMN events.created_on IS 'Дата и время создания события';
COMMENT ON COLUMN events.initiator_id IS 'Идентификатор инициатора события';
COMMENT ON COLUMN events.title IS 'Заголовок события';
COMMENT ON COLUMN events.annotation IS 'Краткое описание события';
COMMENT ON COLUMN events.description IS 'Полное описание события';
COMMENT ON COLUMN events.event_date IS 'Дата и время на которые намечено событие';
COMMENT ON COLUMN events.category_id IS 'Идентификатор категории, к которой относится событие';
COMMENT ON COLUMN events.location IS 'Широта и долгота места проведения события';
COMMENT ON COLUMN events.published_on IS 'Дата и время публикации события';
COMMENT ON COLUMN events.paid IS 'Признак, нужно ли оплачивать событие';
COMMENT ON COLUMN events.participant_limit IS 'Ограничение на количество участников';
COMMENT ON COLUMN events.request_moderation IS 'Признак, нужна ли пре-модерация заявок на участие';
COMMENT ON COLUMN events.confirmed_requests IS 'Количество одобренных заявок на участие в данном событии';
COMMENT ON COLUMN events.state IS 'Состояние события';
