syntax = "proto3";

package stats.message.analyzer;

option java_multiple_files = true;
option java_package = "stats.message.analyzer";

message SimilarEventsRequestProto {
  int64 event_id = 1;         // Идентификатор мероприятия, для которого нужно найти похожие мероприятия.
  int64 user_id = 2;          // Идентификатор пользователя, для которого из выдачи нужно исключить мероприятия, с которыми он уже взаимодействовал.
  int32 max_results = 3;      // Ограничение количества мероприятий в результате выполнения запроса.
}