DROP TABLE IF EXISTS comments;

CREATE TABLE IF NOT EXISTS comments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  event_id BIGINT NOT NULL,
  text VARCHAR(4000) NOT NULL,
  created TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  updated TIMESTAMP WITHOUT TIME ZONE
);

COMMENT ON TABLE comments IS 'Содержит информацию о комментариях';
COMMENT ON COLUMN comments.id IS 'Уникальный идентификатор комментария';
COMMENT ON COLUMN comments.user_id IS 'Идентификатор пользователя, оставившего комментарий';
COMMENT ON COLUMN comments.event_id IS 'Идентификатор события';
COMMENT ON COLUMN comments.text IS 'Текст комментария';
COMMENT ON COLUMN comments.created IS 'Дата и время создания комментария';
COMMENT ON COLUMN comments.updated IS 'Дата и время изменения комментария';